### ISSUE TITLE
Unable to use .ts extension for webpack config

### ISSUE THREAD

**Issue by redappleorigin** [vlazh/node-hot-loader#12]
webpack allows using webpack.config.ts. The issue seems to be that babel requires you to add an argument of  --extensions ".ts" for it to work. There doesn't seem to be a way to add accepted extensions to .babelrc.

**Comment by vladzdev** [comment]
Have you tried instructions from [webpack docs](https://webpack.js.org/configuration/configuration-languages/#typescript)?

**Comment by redappleorigin** [comment]
Yes sir, I read the docs. It's not webpack's fault. Webpack allows you to use webpack.config.ts. The issue seems to be at https://github.com/vlazh/node-hot-loader/blob/master/src/loader.js#L96-L97 . When I added the "extensions" options and specified ".ts", it worked. I had to create a .babelrc file as well. But just having a way to pass extensions down to babel-register should be enough.

**Comment by vladzdev** [comment]
I think babel-register not used for webpack.config.ts. Webpack might be uses ts-node for that. Could you show your webpack config and how you call webpack and node-hot-loader?

**Comment by vladzdev** [comment]
Closed due to inactivity.

**Comment by armarti** [comment]
I made a minimal type declaration for this and I'm too lazy to make a PR so I'll just paste it here in case anyone is interested.

```typescript

declare module 'node-hot-loader' {

    import { Compiler } from 'webpack';

    module 'NodeHotLoaderWebpackPlugin' {

        export interface INodeHotLoaderWebpackPluginOptions {
            // true - always launch entries
            // false (default) - launch entries only in watch mode
            force?: boolean;
            // For example ['--key', 'key value']
            fork?: boolean | string[];
            // For example ['--arg1', 'arg2']
            args?: string[];
            //
            logLevel?: string;
            inMemory?: boolean;
        }

        export default class NodeHotLoaderWebpackPlugin {
            constructor(options: INodeHotLoaderWebpackPluginOptions);
            apply(compiler: Compiler): void;
        }
    }
}
```
