### ISSUE TITLE
Can I not write to disk?

### ISSUE THREAD

**Issue by FishOrBear** [vlazh/node-hot-loader#13]
Run in memory, just like Webpack-dev-server.

**Comment by vladzdev** [comment]
It's not possible now, may be in the future.

**Comment by FishOrBear** [comment]
Do you have any ideas?

Implement this feature

**Comment by FishOrBear** [comment]
If you use ' Nodemon ', you will be able to implement an automatic restart of the app.

The problem I'm having now is that I started the app in memory, but I couldn't implement the thermal update. If I use ' Nodemon ' to launch an app in a file, then I can implement hot updates and automatically restart apps.

**Comment by vladzdev** [comment]
I suppose, with Nodemon you just restart your app without hot update (by webpack).
I don't remember exactly but earlier I have run into some problems with running app in memory with node-hot-loader.

**Comment by FishOrBear** [comment]
I want to reboot when I need it to restart, hot updates when hot updates are needed.

**Comment by vladzdev** [comment]
I found the reason - webpack can't load updated modules from memory-fs. Look at the [source](https://github.com/webpack/webpack/blob/master/lib/node/NodeMainTemplate.runtime.js).
So I close this issue for now. Feel free to reopen if you will have some ideas.
