### ISSUE TITLE
Support for multiple configurations

### ISSUE THREAD

**Issue by daniel-ac-martin** [vlazh/node-hot-loader#18]
Webpack allows multiple configurations to be defined within a single configuration file. (See: https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations )

It seems to me that this would be useful for isomorphic web applications to avoid the separate `webpack.config.server.js` file. However, one would need to specify to node-hot-loader which config to pick from the file.

This doesn't appear to be supported at the moment. (Am I wrong?)

Is this something that you would consider supporting?

**Comment by vladzdev** [comment]
It should work. Just set target to 'node' in one of config.

**Comment by daniel-ac-martin** [comment]
Ah, clever. I didn't think of that! :-)
