### ISSUE TITLE
HELP ME - how to use HMR view engine pug

### ISSUE THREAD

**Issue by long-hp** [vlazh/node-hot-loader#2]
`let router = require('./router.js');`
`app.set('views', path.resolve(__dirname, entryPath));`
`app.locals.basedir = path.resolve(__dirname, appConfig.folders.path);`
`app.set('view engine', 'pug');`
`app.use('/', router);`

**Comment by vladzdev** [comment]
Explain your problem, please.

**Comment by long-hp** [comment]
I want to use HMR for pugjs
I use express
how to auto update it without reloading the page

**Comment by vladzdev** [comment]
node-hot-loader working on server side, not in browser.
You can see how works react-hot-loader.
Also you can see some links:
https://stackoverflow.com/questions/46858272/how-to-get-webpack-hot-reload-to-detect-changes-in-pug-express
https://gist.github.com/helpse/a3419706c1d937470fedf31800b7f625

**Comment by long-hp** [comment]
Tks (Y)
