### ISSUE TITLE
Auto-restart stops working when file is changed twice

### ISSUE THREAD

**Issue by leo-buneev** [vlazh/node-hot-loader#22]
Hi!

Thank you for amazing module, didn't even thought that is possible.

It mostly works very well, but I've encountered one annoying issue. If i change the same file twice fast, something breaks in auto-reload functionality.

Normal sequence (file edited once):

1. *file edited*
2. [Webpack] Compiling...
3. [Webpack] Compiled successfully.
4. [HMR] Ignored an update to unaccepted module
5. [HMR] AutoRestart is on. Restart process...
6. Process restarted

Bad sequence (file edited twice quickly enough (when first compile is still in progress) )

1. *file edited*
2. [Webpack] Compiling...
3. *file edited once again*
3. [Webpack] Compiled successfully.
4. [Webpack] Compiling...
5. [Webpack] Compiled successfully
4. [HMR] Cannot find update. You need to restart the application!
5. [HMR] Cannot find update. You need to restart the application!

And no restart happens. All subsequent updates trigger same message and no restart.

Is it possible to improve this usecase (restart the app)? I've tried to fix it in fork, but have trouble understanding inner workings of HMR.

**Comment by vladzdev** [comment]
Hi @leo-buneev,
What version of webpack you use?

**Comment by vladzdev** [comment]
I can't reproduse this behaviour.

**Comment by leo-buneev** [comment]
Node: 16.0.0
Webpack: 5.24.3

 Thanks for looking, I'll create a reproduction repo later today

**Comment by vladzdev** [comment]
Closed due to inactivity.
