### ISSUE TITLE
Can't install in development mode

### ISSUE THREAD

**Issue by jaens** [vlazh/node-hot-loader#23]
Cloning the repo and trying to install the packages results in the following error:
```
npm ERR! code E401
npm ERR! Incorrect or missing password.
```

coming from

```
 GET https://npm.pkg.github.com/@js-toolkit%2Fconfigs: Unauthorized - 401
```

Looks like there's an `.npmrc` set up that uses a custom npm registry that other developers can not access by default?

**Comment by vladzdev** [comment]
The package [@js-toolkit/configs](https://github.com/js-toolkit/configs) is public. Do you still have a problem?

**Comment by vladzdev** [comment]
I got it. Fixed.
