### ISSUE TITLE
Sourcemap/debug breakpoint support

### ISSUE THREAD

**Issue by slatlasdev** [vlazh/node-hot-loader#25]
Hi

Is it possible to get sourcemaps/debug breakpoints in VS Code/WebStorm working? 

I have tried to get interactive debugging working by adding the `devtool: 'cheap-module-source-map'` setting, but neither VSCode or WebStorm is able to resolve the files back to the original source code.

It may be complicated by the fact that I am running `node-hot-loader` via TypeScript, like so:

`ts-node node_modules/.bin/node-hot --config webpack.server.ts`

Have you been ever able to get interactive debugging working with `node-hot-loader`, and is it possible to post an example configuration if so?

**Comment by vladzdev** [comment]
`source-map-support` plugin will be installed if you configure `devtool` in your webpack config, so sourcemaps should work.
Have you try to start server without node-hot-loader? Will your IDE be working correctly?

**Comment by vladzdev** [comment]
Also have you enabled sourcemap in tsconfig?

**Comment by slatlasdev** [comment]
Hi

Thanks for the tips.

I just tried running the compiled Webpack output without `node-hot-loader` and the sourcemapping/breakpoints work correctly. I do have `sourcemap` enabled in `tsconfig.json`.

I am wondering whether the problem is launching `node-hot-loader` via `ts-loader`. I prefer to write my Webpack configuration in TypeScript, which is why I have done it this way.

I will try to remove it from the process and see if that fixes it.

**Comment by vladzdev** [comment]
Maby it worth to try to launch webpack-dev-server like [this](https://webpack.js.org/configuration/configuration-languages/) and then check debugging?

**Comment by vladzdev** [comment]
`node-hot-loader` works throught webpack so it worth to check raw webpack and debugging in IDE in order to narrow the problem.

**Comment by slatlasdev** [comment]
OK, so it turned out all I had to do is add `--fork` to the `node-hot-loader` flags.

Basically it seems like VSCode was not loading the new sourcemaps that were compiled and generated after the initial load, but when it forks to a new process and it attaches a new debugger to that forked instance, the sourcemaps already exist at that point, so it is able to properly detect them.

**Comment by vladzdev** [comment]
Great! I'll add this tip to readme.

**Comment by slatlasdev** [comment]
Awesome! I also wanted to mention that for the `devtool` option, I had to use one of the `eval` sourcemaps to get hot reloading working correctly. Otherwise it would get confused about which of the many `.map` files that gets generated to use and breakpoints would stop working after the first hot reload. I also tried `inline` instead of `eval` but that was unreliable as well.
