### ISSUE TITLE
Error when using with socket.io

### ISSUE THREAD

**Issue by oonsamyi** [vlazh/node-hot-loader#3]
I tried to use this library in the application with the express - everything is fine! I also tried to connect the socket.io library, but I got an error when I changed express router and refreshed the page in the browser.
The error is as follows:

**Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client**
&nbsp;&nbsp;&nbsp;&nbsp;at validateHeader (_http_outgoing.js:503:11)
&nbsp;&nbsp;&nbsp;&nbsp;at ServerResponse.setHeader (_http_outgoing.js:510:3)
&nbsp;&nbsp;&nbsp;&nbsp;at ServerResponse.header (/myproject/node_modules/express/lib/response.js:767:10)
&nbsp;&nbsp;&nbsp;&nbsp;at ServerResponse.contentType (/myproject/node_modules/express/lib/response.js:595:15)
&nbsp;&nbsp;&nbsp;&nbsp;at ServerResponse.send (/myproject/node_modules/express/lib/response.js:145:14)
&nbsp;&nbsp;&nbsp;&nbsp;at app.get (/myproject/build/back/0.e82fa0b64b13baf96886.hot-update.js:22:31)
&nbsp;&nbsp;&nbsp;&nbsp;at Layer.handle [as handle_request] (/myproject/node_modules/express/lib/router/layer.js:95:5)
&nbsp;&nbsp;&nbsp;&nbsp;at next (/myproject/node_modules/express/lib/router/route.js:137:13)
&nbsp;&nbsp;&nbsp;&nbsp;at Route.dispatch (/myproject/node_modules/express/lib/router/route.js:112:3)
&nbsp;&nbsp;&nbsp;&nbsp;at Layer.handle [as handle_request] (/myproject/node_modules/express/lib/router/layer.js:95:5)
_http_outgoing.js:503
&nbsp;&nbsp;&nbsp;&nbsp;throw new errors.Error('ERR_HTTP_HEADERS_SENT', 'set');

#### Dependencies:
-  "node-hot-loader": "^1.6.0"
-  "express": "^4.16.2"
-  "socket.io": "^2.0.4"
-  "socket.io-client": "^2.0.4"

#### Engines:
- "node": "^9.7.1"
-  "yarn": "^1.5.1"

#### Code
&nbsp;&nbsp;&nbsp;&nbsp;**server.js**
```javascript
/* @flow */

import withSocket from 'socket.io'
import { app } from './express'

const PORT = process.env.PORT || 3000
const server = app.listen(PORT, () =>
  console.log(`Server is running at ${PORT} port`),
)
const io = withSocket(server, { path: '/ws' })

io.on('connection', socket => {
  console.log('connection')
  socket.emit('message', 'hello')
})

if (module.hot && typeof module.hot.accept == 'function') {
  let currentApp = app

  module.hot.accept('./express', async () => {
    server.removeListener('request', currentApp)

    currentApp = require('./express').app
    server.on('request', currentApp)

    console.log('Server reloaded!')
  })

  module.hot.accept()
  module.hot.dispose(() => {
    console.log('Disposing entry module...')
    server.close()
  })
}
```
&nbsp;&nbsp;&nbsp;&nbsp;**express.js**
```javascript
/* @flow */

import express from 'express'
import { resolve } from 'path'

const staticPath = resolve(__dirname, '../front')
export const app = express()

app.use(express.static(staticPath))
app.get('/test', (_, res) => res.send('Hello world!'))
```
&nbsp;&nbsp;&nbsp;&nbsp;**client.js**
```javascript
/* @flow */

import io from 'socket.io-client'

const socket = io(undefined, { path: '/ws' })
socket.on('connect', () => console.log('connect'))
socket.on('disconnect', () => console.log('disconnect'))
socket.on('message', msg => console.log(msg))
```
Any ideas?

**Comment by vladzdev** [comment]
Can you share simple project with github? I will try to reproduce that error.

**Comment by vladzdev** [comment]
Closed due to inactivity.

**Comment by couturecraigj** [comment]
I think that this is an issue with Socket.IO.  I am hitting similar issues.  I put a piece in my code that checks for `res.headersSent` but that does not solve the issue that things are not being hot-reloaded.  I simply add a console.log in my app and it still logs to the console after I comment it out which means it is creating duplicates and not properly disposing of socket.io.  It must have something to do with how socket.io attaches the HTTP server.

**Comment by vladzdev** [comment]
Have a look at https://github.com/socketio/engine.io.
Maybe need call oldSocketServer.close() and then call newSocketServer.attach(httpServer) or something simular.

**Comment by couturecraigj** [comment]
Maybe I do not fully understand where to put this but I have already done this.  The biggest thing is that I am trying to use express and socket.io <http://socket.io/> at the same time.

**Comment by couturecraigj** [comment]
I figured out a way to get it to work.  I think my biggest issue is that it was conflicting with Apollo Server.  So now I am importing them separately.  The biggest issue now is I am hitting max event listeners limit.
