### ISSUE TITLE
Question: How to HMR React Front End and Express Backend?

### ISSUE THREAD

**Issue by matt-d-rat** [vlazh/node-hot-loader#5]
Hello, I just came across your repo and I am interested in using this to HMR my back-end API. What is not clear from the docs is how to set this up for both the front-end and back-end simulatenously.

My current setup is very similar to the [react-hot-boilerplate](https://github.com/gaearon/react-hot-boilerplate/blob/master/server.js) example, in that I have a `server.js` file which sets up the express server for HMR, this however is purely used for development.

This works well for the React app, but now I wish to work on a express server to create a REST API for the application.

My question: Do I have two different servers running HMR, one for the front-end React app, and one for the back-end express API? Or can I set this up in such a way as to have one HMR which will handle changes both to the front-end and the back-end?

A simple example demonstrating this setup would be most appreciated.

**Comment by vladzdev** [comment]
Hello,
You will have two HMR, one for react app (browser), another for express app.
Try this:
Add webpack config for your express app (for server.js), for example, webpack.config.server.js. Look at [simple-example](https://github.com/vlazh/node-hot-loader/tree/master/examples/simple-example). Don't forget to configure `externals` for node app in webpack config. And then just run `node-hot --config webpack.config.server.js`. node-hot-loader compile you entry (server.js) with webpack and then start it.
Also look at [README](https://github.com/vlazh/node-hot-loader/blob/master/README.md#express-hot-reload-example) for correct hot reload express app.

**Comment by matt-d-rat** [comment]
Thanks for getting back to me so quickly. Okay, that makes sense. I will setup another webpack config for the server. Thanks for the help!
