### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by mischnic** [vlazh/node-hot-loader#6]
A cli option to select between:
- verbose logging (as now)
- "Updated" and errors
- only on errors (when an update failed)

would be great.

```
[HMR] Waiting webpack...
Webpack    9 modules
Webpack Compiled successfully.
[HMR] Launch assets in forked process.
[HMR] Waiting for update signal from webpack...
Webpack Compiling...
Webpack    9 modules
Webpack Compiled successfully.
[HMR] Checking for updates...
[HMR] Updated modules:
[HMR]  - ./src/app.js
[HMR] App is up to date.
```

**Comment by vladzdev** [comment]
Added in [1.10.0](https://github.com/vlazh/node-hot-loader/blob/master/CHANGELOG.md#1100-2018-07-30).
For webpack logging use [webpack stats configuration](https://webpack.js.org/configuration/stats/#stats).
If you want different log level for [node-hot-loader](https://github.com/vlazh/node-hot-loader) use [logLevel option](https://github.com/vlazh/node-hot-loader#options).
What are you think?

**Comment by mischnic** [comment]
Perfect! 👍
