### ISSUE TITLE
Is it possible to run node with --inspect-brk?

### ISSUE THREAD

**Issue by danil-z** [vlazh/node-hot-loader#9]
Is it possible to run node with --inspect-brk?
I want to catch something during bootstrap of my app and if I connect manually it's too late to attach...

**Comment by vladzdev** [comment]
It's not possible until version 1.12.0.
It's good idea and I added support for node exec arguments in [1.12.0](https://github.com/vlazh/node-hot-loader/blob/master/CHANGELOG.md#1120-2018-09-20).
Now you can pass exec arguments with `--fork` [option](https://github.com/vlazh/node-hot-loader/blob/master/README.md#options):
```sh
node-hot --fork=--inspect-brk
```

**Comment by danil-z** [comment]
Thanks!

**Comment by danil-z** [comment]
It's not working... It still run whole app before I had a chance to attach debugger to it

`> node-hot --fork=--inspect-brk --config webpack.dev.js

[HMR] Waiting webpack...
[HMR] Launch assets in forked process.
[HMR] Waiting for update signal from webpack...
[Nest] 14960   - 9/20/2018, 2:53:34 PM   [NestFactory] Starting Nest application...
[Nest] 14960   - 9/20/2018, 2:53:34 PM   [InstanceLoader] ApplicationModule dependencies initialized +19ms
[Nest] 14960   - 9/20/2018, 2:53:34 PM   [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 14960   - 9/20/2018, 2:53:34 PM   [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 14960   - 9/20/2018, 2:53:34 PM   [InstanceLoader] GraphQLModule dependencies initialized +1ms
[Nest] 14960   - 9/20/2018, 2:53:34 PM   [NestApplication] Nest application successfully started +196ms`

**Comment by vladzdev** [comment]
Fixed some errors. Try 1.12.1.
